# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
    ]
