# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1)),
                ('c_select', models.BooleanField(default=True)),
                ('c_belong', models.BooleanField(default=False)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.IntegerField(default=0)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='c_order',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='axf.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.User'),
        ),
    ]
